name: vmd
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tqdm
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - torchvision
  - pip
  - pip:
    - medpy
    - apex
